### ISSUE TITLE
Initialization Output labels are confusing

### ISSUE THREAD

**Issue by swoogles** [EffectOrientedProgramming/book#431]
`makeY` is prepended to a bunch of output such that it's not obvious what is output from within `makeY` and what is output from the caller of `makeY`

<img width="602" alt="Screenshot 2024-07-11 at 8 48 10 AM" src="https://github.com/EffectOrientedProgramming/book/assets/2054940/4b9d5a86-7def-41a4-aba5-1b576f5905d4">

**Comment by BruceEckel** [comment]
Have a look now. Not necessarily the final product; we could add a function to strip out more.

**Comment by swoogles** [comment]
That might have helped in other ways, but I'm specifically talking about how many output lines are prepended by "makeY"

**Comment by swoogles** [comment]
Yeah, the output is definitely improved in the new version, but the heart of this ticket remains:
```
makeY: zio.ZIO
makeY Creating Y
makeY returns: Y()
makeY.run returned Y()
```

**Comment by BruceEckel** [comment]
Have a look at it now.
