### ISSUE TITLE
import zio.test.* does not work in mdoc maybe only on windows

### ISSUE THREAD

**Issue by jamesward** [EffectOrientedProgramming/book#451]
```
[info] error: <input>:90:5:
[info] Reference to test is ambiguous.
[info] It is both imported by import zio._
[info] and imported subsequently by import zio.test._
[info]     test("random is random"):
[info]     ^^^^
```

**Comment by swoogles** [comment]
Do we really think this is a windows thing? That would be unprecedented for this type of error.
It's possible, but seems unlikely...

**Comment by jamesward** [comment]
yeah, it makes no sense why this would be different on windows, but some far that is the only idea I have for why we are seeing different behavior.

**Comment by jamesward** [comment]
So I think this is coming up on Windows only because in preprocessing we remove the problematic import but are only matching on `\n` new lines:
https://github.com/EffectOrientedProgramming/book/blob/main/src/main/scala/mdoc/Main.scala#L453-L454

I'm going to try and change it to match on any new lines.
